### ISSUE TITLE
404: lyrist.vercel.app

### ISSUE THREAD

**Issue by ghost** [asrvd/lyrist#1]
API isn't working ... brought up 404 error. I tried deploying myself, although whenever I entered lyrics it'd always show "lyrics not found"

**Comment by asrvd** [comment]
sorry for that, someone was spamming the API with millions of requests (almost used up all my usage quota for this month), the API will be back soon with some sort of ratelimiting

**Comment by ghost** [comment]
all good, thats too  bad. such a great resource, yet people take advantage and abuse.

**Comment by asrvd** [comment]
the API is back up now, and if you can even deploy it yourself now without any issues (there was an issue with the package i was using)
