### ISSUE TITLE
Is it possible to return something for empty/no lyrics/instrumental songs?

### ISSUE THREAD

**Issue by lachlan-00** [asrvd/lyrist#4]
I know it's sort of the opposite of lyrics but is there a way to say "no lyrics for this song" somehow?

I don't know if there's a standard for it or a way to differentiate between none found and identified with no lyrics

**Comment by asrvd** [comment]
sorry for replying so late, I think I need to check what are the api responses for both cases, maybe we can differentiate bw them

**Comment by asrvd** [comment]
unfortunately, I don't think this will be possible - it falls in the same category as "lyrics not found"

**Comment by lachlan-00** [comment]
Thanks for looking. lets close this then
