### ISSUE TITLE
[BUG] Unable to make api request with axios

### ISSUE THREAD

**Issue by kerichdev** [asrvd/lyrist#7]
`Access to XMLHttpRequest at 'https://lyrist.vercel.app/api/Sovereign%20Self/Thou' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

Can't make api requests from own project, it's simply not letting me do so because CORS policy isnt properly configured for an api.

**Comment by asrvd** [comment]
fixed https://github.com/asrvd/lyrist/commit/3f0dfab7d73707851b6150e2a97d447a7f325064
